version: '3.8'
services:
  mysql:
    image: "mysql:8.0.27"
    restart: always
    hostname: "mysql.local"
    container_name: "mysql"
    ports:
      - "3306:3306"
    networks:
      local:
        aliases:
          - "mysql.local"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: "redis:alpine3.13"
    hostname: "redis.local"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      local:
        aliases:
          - "redis.local"
  zookeeper:
    image: "zookeeper:3.7.0"
    hostname: "zookeeper.local"
    container_name: "zookeeper"
    networks:
      local:
        aliases:
          - "zookeeper.local"
  kafka:
    image: "wurstmeister/kafka:2.13-2.7.0"
    hostname: "kafka.local"
    container_name: "kafka"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      local:
        aliases:
          - "kafka.local"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
networks:
  local:
    driver: bridge