version: '3.8'
services:
  mysql:
    image: "mysql:8.0.27"
    restart: always
    hostname: "mysql.local"
    container_name: "mysql"
    ports:
      - "3306:3306"
    networks:
      local:
        aliases:
          - "mysql.local"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - ./data/mysql:/var/lib/mysql
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  redis:
    image: "redis:alpine3.13"
    hostname: "redis.local"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      local:
        aliases:
          - "redis.local"
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  zookeeper:
    image: "zookeeper:3.7.0"
    hostname: "zookeeper.local"
    container_name: "zookeeper"
    networks:
      local:
        aliases:
          - "zookeeper.local"
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  kafka:
    image: "wurstmeister/kafka:2.13-2.7.0"
    hostname: "kafka.local"
    container_name: "kafka"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      local:
        aliases:
          - "kafka.local"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  nacos:
    image: "nacos/nacos-server:2.0.3"
    hostname: "nacos.local"
    container_name: nacos
    networks:
      local:
        aliases:
          - "nacos.local"
    volumes:
      - ./data/nacos/logs:/home/nacos/logs
      - ./config/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    depends_on:
      - nacos-mysql
    environment:
      PREFER_HOST_MODE: ip
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: nacos-mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: ${NACOS_MYSQL_USER}
      MYSQL_SERVICE_PASSWORD: ${NACOS_MYSQL_PASSWORD}
      MYSQL_SERVICE_DB_NAME: ${NACOS_MYSQL_DB_NAME}
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  nacos-mysql:
    image: nacos/nacos-mysql:8.0.16
    container_name: nacos-mysql
    hostname: nacos-mysql.local
    restart: always
    networks:
      local:
        aliases:
          - "nacos-mysql.local"
    volumes:
      - ./data/nacos/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_DATABASE: ${NACOS_MYSQL_DB_NAME}
      MYSQL_USER: ${NACOS_MYSQL_USER}
      MYSQL_PASSWORD: ${NACOS_MYSQL_PASSWORD}
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    container_name: elastic
    hostname: elastic.local
    networks:
      local:
        aliases:
          - "elastic.local"
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.0
    container_name: kibana
    hostname: kibana.local
    networks:
      local:
        aliases:
          - "kibana.local"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  mongo:
    image: mongo:5.0.5
    container_name: mongo
    hostname: mongo.local
    ports:
      - "27017:27017"
    networks:
      local:
        aliases:
          - "mongo.local"
    environment:
      TZ: ${MONGO_TZ}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - "${MONGO_DIR}/data:/data/db"
      - "${MONGO_DIR}/logs:/data/logs"
      - "${MONGO_DIR}/setup:/docker-entrypoint-initdb.d"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
networks:
  local:
    driver: bridge