version: '3.8'
networks:
  sky-walking:
    driver: bridge
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    container_name: elastic
    hostname: elastic
    networks:
      sky-walking:
        aliases:
          - "elastic.sky-walking"
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  oap:
    image: apache/skywalking-oap-server:9.2.0
    container_name: oap
    hostname: oap
    depends_on:
      elastic:
        condition: service_healthy
    ports:
      - "11800:11800"
      - "12800:12800"
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elastic:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
    networks:
      sky-walking:
        aliases:
          - "oap.sky-walking"
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  ui:
    image: apache/skywalking-ui:9.2.0
    container_name: ui
    hostname: ui
    ports:
      - "80:8080"
    depends_on:
      oap:
        condition: service_healthy
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      SW_ZIPKIN_ADDRESS: http://oap:9412
    networks:
      sky-walking:
        aliases:
          - "ui.sky-walking"
    logging:
      options:
        max-size: "200k"
        max-file: "10"